### ISSUE TITLE
你好 这里有一个报错 请教您一下

### ISSUE THREAD

**Issue by jy2020-start** [xiaoleimiao/UDTL_Lable_Inconsistent#1]
datasets文件夹下 
from datasets.CWRU_label_inconsistent import CWRU_inconsistent
from datasets.CWRUFFT_label_inconsistent import CWRUFFT_inconsistent
总是会报如下错误：TypeError: 'module' object is not callable（“模块”对象不可调用）
但是我认真比对了代码 并没有出现包的引入错误 这是为什么呢？

**Comment by jy2020-start** [comment]
错误描述：
Traceback (most recent call last):
  File "train_advanced.py", line 85, in <module>
    trainer.setup()
  File "D:\PY2020\UDTL_Lable_Inconsistent-main\utils\train_utils_open_univ.py", line 58, in setup
    self.datasets['source_train'], self.datasets['source_val'], self.datasets['target_train'], self.datasets['target_val'] = Dataset(args.data_dir, args.transfer_task, arg
s.normlizetype).data_split(transfer_learning=True)
TypeError: 'module' object is not callable

是在运行train_utils_combines或者train_utils_open_univ两个执行文件中出现的错误 能否请求一下您的帮助 感谢

**Comment by jy2020-start** [comment]
您好 已经通过更改py文件和内部类名模块名解决了问题 感谢您分享的代码
